# Just change the cron time and Set timezone lines if it necessarry. Or secret variables if you set them different.

name: Rebuild HF
on:
  schedule:
    - cron: '0 */2 * * *' # Runs in every 2 hours to build it. You can change the 2 to whatever you want.
  workflow_dispatch: # Manual trigger for workflow.

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set timezone to America/New_York
        run: |
          sudo timedatectl set-timezone America/New_York # You can change this lines according to your own time zone.
          export TZ="America/New_York"

      - name: Add timestamp to Dockerfile
        run: |
          NOWDATE=$(date "+%Y-%m-%d %H:%M:%S")
          sed -i "/^RUN pip install/a RUN echo 'Rebuild at $NOWDATE' >> /app/rebuild.log" Dockerfile

      - name: Commit and push it HuggingFace
        run: |
          git config --global user.name "🔥 Latte HF Rebuilder 🔥"
          git config --global user.email "GitLatte@github.com"
          git add Dockerfile
          git commit -m "♻️ Success rebuild to HuggingFace space $NOWDATE"
          git push -f https://oauth2:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_SPACE_NAME }} main
        env:
          HF_SPACE_NAME: ${{ vars.HF_SPACE_NAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
